### ISSUE TITLE
Implement the basic architecture

### ISSUE THREAD

**Issue by thervh70** [thervh70/ContextProject_RDD#4]
This will be done using interfaces.

**Comment by Exclaminator** [comment]
Doenst it need to be fully designed first?

**Comment by thervh70** [comment]
@Exclaminator Yes but this issue is a low priority issue that might be done this week. Once we have build a certain architecture we will be able to code this using interfaces. This will be the basis for the work to be done in week 2 of the project.

**Comment by mpsijm** [comment]
Will now be done in sub-issues #5, #8 and #9, and a full implementation will be made here.

**Comment by breijm** [comment]
If it's a duplicate don't forget to close this issue
